---
name: Integration
on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - synchronize
    branches:
      - main
      - stable-*

jobs:
  splitter:
    runs-on: ubuntu-latest
    env:
      source_dir: "./source"
    outputs:
      jobs: ${{ steps.run-splitter.outputs.jobs }}
      targets: ${{ steps.run-splitter.outputs.targets }}
    steps:
      - name: Checkout collection
        uses: actions/checkout@v4
        with:
          path: ${{ env.source_dir }}
          fetch-depth: "0"

      - name: list changes for pull request
        id: run-splitter
        uses: ansible/cloud-content-ci-automation/.github/actions/ansible_test_splitter@0b891487c4170ef856f02313c66cb1c776814c42
        with:
          collections_to_test: "${{ env.source_dir }}"
          total_jobs: 4
          base_ref: "${{ github.base_ref }}"

      - name: Display splitter output
        run: |
          echo "jobs=${{ steps.run-splitter.outputs.jobs }}"
          echo "targets=${{ steps.run-splitter.outputs.targets }}"
        shell: bash
  test:
    runs-on: ubuntu-latest
    needs:
      - splitter
    if: ${{ needs.splitter.outputs.targets != '' }}

    env:
      source: "./source"
      ansible_version: "milestone"
      python_version: "3.13"
      ansible_test_splitter_targets: "${{ needs.splitter.outputs.targets }}"
    strategy:
      fail-fast: false
      matrix:
        workflow-id: ${{ fromJson(needs.splitter.outputs.jobs) }}
    name: "integration-${{ matrix.workflow-id }}"
    steps:
      - name: Read job targets
        id: read-targets
        uses: ansible/cloud-content-ci-automation/.github/actions/ansible_read_targets@0b891487c4170ef856f02313c66cb1c776814c42
        with:
          job_id: "${{ matrix.workflow-id }}"
          all_targets: "${{ env.ansible_test_splitter_targets }}"

      - name: Display ansible test targets
        run: |
          echo "ansible_test_targets -> ${{ steps.read-targets.outputs.job_targets }}"
        shell: bash

      - name: Create AWS session credentials
        uses: ansible/ansible-test-auth@v1

      - name: Run integration tests
        uses: ansible-community/ansible-test-gh-action@d3a8ec7a59694e25e210fcd44738910149537f0e
        with:
          ansible-core-version: ${{ env.ansible_version }}
          origin-python-version: ${{ env.python_version }}
          testing-type: integration
          target: ${{ steps.read-targets.outputs.job_targets }}
          test-deps: >-
            git+https://github.com/ansible-collections/amazon.aws.git,main
            git+https://github.com/ansible-collections/community.aws.git,main
            community.general
          pre-test-cmd: python -m pip install -r tests/integration/requirements.txt
